### ISSUE TITLE
security certificate invalid for stpeter.im

### ISSUE THREAD

**Issue by mlinksva** [stpeter/stpeter.github.io#2]
Visiting https://stpeter.im my browser warns me:

> stpeter.im uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

Links in your feed (how I got there) are https.

http://stpeter.im works. AFAIK to use https with a custom domain served by GitHub pages you need something like https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by stpeter** [comment]
Hi Mike, thanks for the tip! While I figure out the HTTPS story, I'm going to change all URL pointers so that they're HTTP.

**Comment by stpeter** [comment]
I've been thinking about this more and I'm not sure how comfortable I am with relying on Cloudflare. Just more centralization. Of course now things are centralized at GitHub, too. Sigh.

**Comment by stpeter** [comment]
This is working again, thanks to GitHub's collaboration with Let's Encrypt. Security FTW!
